### ISSUE TITLE
Links and screenshots are invalid

### ISSUE THREAD

**Issue by ghost** [SAP-samples/btp-bridge-framework#10]
Hi @I868421 

The links and screenshots in https://github.com/SAP-samples/btp-bridge-framework/tree/main/S4HANA are inaccessible/unavailable. 

Thanks.

**Comment by viancu** [comment]
Hi Thien, 

We are working on updating that documentation for the future, so for the time being we have removed that directory. The readme there describes some custom code for enabling Purchase Order events to create Teams notifications. More generic documentation will follow.

Best,
Victor
