### ISSUE TITLE
Error after run ./BTPSA

### ISSUE THREAD

**Issue by ABVN-Huy** [SAP-samples/btp-bridge-framework#11]
Hi Alex,

I am Huy from Abeam, I am following your github to set up btp bridge framework
https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/automation/Automation%20Overview.md

After I run ./BTPSA and login to CLI, the error occurs as below
 
![image](https://user-images.githubusercontent.com/115139053/233545363-a68ec23e-5095-48a8-801c-452adf1d1fe5.png)

I attached all the log files in log folder and parameter json file (change to .txt type as github cannot upload .log files). Could you have a look and give me some advices ?
[metadata_log.txt](https://github.com/SAP-samples/btp-bridge-framework/files/11292374/metadata_log.txt)
[docker-configuration.txt](https://github.com/SAP-samples/btp-bridge-framework/files/11292375/docker-configuration.txt)
[parameters.txt](https://github.com/SAP-samples/btp-bridge-framework/files/11292376/parameters.txt)
[pwsh.txt](https://github.com/SAP-samples/btp-bridge-framework/files/11292377/pwsh.txt)
[script.txt](https://github.com/SAP-samples/btp-bridge-framework/files/11292378/script.txt)

**Comment by AFK-Python** [comment]
Hi Huy,

The logs and screenshot seem to contain the correct information; however, I would double check one more time that the values in parameters.json are correct.

Outside of that, are you using a BTP Trial account? Based on the info from the logs I suspect that the answer is no, but I want to double check this. 

Lastly, could you run that btp command that failed in isolation? It seems the error messages was not caught. For reference, the command:

```
btp --format json list accounts/entitlements --global-account <Global_Account_Subdomain_Value>
```

`Global_Account_Subdomain_Value` should be the set to be the same as your `globalaccount` value from parameters.json. Note, you may need to login first. Here is the command to login to your btp cli:

```
btp login --url https://cpcli.cf.eu10.hana.ondemand.com
```

Please let me know what the output of the btp format command is, if it errors. If it is working, you should see a lot of information about your btp account in json formatting, and if that is the case, I would re-run the tool again.

**One more thing**, this section in parameters.json should also be updated:

```
"enterpriseApp": {
      "emails": [<email1>, <email2>]
    }
```

These emails dictate who will have access to Bridge once it is uploaded to Teams. I suggest changing this array to whatever emails suit your needs. I will go ahead and update the documentation in the automation section to include this information.

**Comment by ghost** [comment]
Hi @AFK-Python (Alex):

* Huy and I are working on this. I elaborate more in this. We figured out that authorization missing (global-account-viewer) is the rootcause. 

* This comes to a question the need of assignment for global-account-viewer role as we have to request the role. Our global account is not trial.

* As check the btpsa file in docker, not only read the account detail and entitlement. The command also create the service, assign entitlement which I think it's not under our control.

* Can you help to share which service/entitlements will be created at the end if we run the set up successfully.

Thank you.
Thien

**Comment by ghost** [comment]
* we can run in the trial account and get the log successful. can you help to confirm these services use only for this use-case or advise us if there are services need to entitle.
```
[2023-04-24 08:30:12] INFO       : Get list of available services and app subsciptions for defined region >us10<
[2023-04-24 08:30:12] RUN COMMAND: btp --format json list accounts/entitlement --global-account 'a23c10d4trial-ga'
[2023-04-24 08:30:15] SUCCESS    : service  >application-logs< with plan >lite< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : service  >xsuaa< with plan >application< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : service  >xsuaa< with plan >apiaccess< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : service  >destination< with plan >lite< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : service  >connectivity< with plan >lite< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : service  >enterprise-messaging< with plan >dev< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : service  >enterprise-messaging-hub< with plan >standard< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : Use case supported in your global account!
```
Thank you.

**Comment by AFK-Python** [comment]
Hi Thien,

Yes, you will need the roles needed to create services - I can provide those if desired; however, a trial account will also work to setup Bridge and might be the better way to go in this case.

We will be releasing an updated container for trial accounts today as the current container use case provisions services that may not available to a trial account. 

The services that should end up provisioned in the trial version are the following:

```
####################################################################################################
# Checking if all configured services & app subscriptions are available on your global account
####################################################################################################
[2023-04-24 18:01:56] INFO       : Get list of available services and app subsciptions for defined region >us10<
[2023-04-24 18:01:56] RUN COMMAND: btp --format json list accounts/entitlement --global-account <global_account>
[2023-04-24 18:01:58] SUCCESS    : service  >application-logs< with plan >lite< in region >us10< IS AVAILABLE
[2023-04-24 18:01:58] SUCCESS    : service  >xsuaa< with plan >application< in region >us10< IS AVAILABLE
[2023-04-24 18:01:58] SUCCESS    : service  >xsuaa< with plan >apiaccess< in region >us10< IS AVAILABLE
[2023-04-24 18:01:58] SUCCESS    : service  >destination< with plan >lite< in region >us10< IS AVAILABLE
[2023-04-24 18:01:58] SUCCESS    : service  >connectivity< with plan >lite< in region >us10< IS AVAILABLE
[2023-04-24 18:01:58] SUCCESS    : Use case supported in your global account!
```

The logs displayed above in your comment include the following additional services:

```
[2023-04-24 08:30:15] SUCCESS    : service  >enterprise-messaging< with plan >dev< in region >us10< IS AVAILABLE
[2023-04-24 08:30:15] SUCCESS    : service  >enterprise-messaging-hub< with plan >standard< in region >us10< IS AVAILABLE
```

These services are intended for the full version, as they may not work for all trial accounts. If the tool works as is with your trial account, then you should be good to go! Otherwise, the trial version of the docker image will be ready shortly - we apologize for any delays that this may have caused.
 
Best,
Alex

**Comment by ghost** [comment]
Hi @AFK-Python (Alex),

* We're much appreciated the feedback; it helps a lot.
* FYI, we are going with Test Driven Development project, and BTP subscription is PAYG (if I remember correctly).
> Yes, you will need the roles needed to create services - I can provide those if desired; however, a trial account will also work to setup Bridge and might be the better way to go in this case.
* As our accounts are managed by the admin, we are unable to assign our own roles. It would be helpful if you can share the roles needed to perform all the necessary steps. we will request once.

Thank you,
Thien

**Comment by AFK-Python** [comment]
Hi Thien,

The role collection I have for myself at the global account level is called `Global Account Administrator`. It contains the following roles: `Global Account Admin`, `Global Account Usage Reporting Viewer`, `System Landscape Administrator`, and `User and Role Administrator`.

Also, I'll provide the roles for the subaccount level - just in case - I have the following role collections (with the roles listed underneath each):
 - `Cloud Connector Administrator`
   - `Cloud Connector Administrator`
 - `Connectivity and Destination Administrator`
   - `Cloud Connector Administrator`
   - `Destination Administrator` 
 - `Destination Administrator`
   - `Destination Administrator` 
 - `Enterprise Messaging Administrator`
   - `ManageRole`
 - `Subaccount Administrator`
   - `Subaccount Admin`
   - `Cloud Connector Administrator`
   - `Destination Administrator`
   - `Subaccount Service Administrator`
   - `User and Role Administrator` 
 - `Subaccount Service Administrator`
   -  `Subaccount_Service_Admin`

Some of these roles in the subaccount may be redundant (for example the first three role collections seems to overlap); however I know that this configuration will work.

I will be adding a section on this to our documentation as well, so thank you for pointing this out to us.

Please let me know if you have any more questions, our team is always happy to respond to any potential issues users might have.

Best,
Alex

**Comment by AFK-Python** [comment]
Hi Thien,

I just wanted to follow up on my previous comment, as I was looking into my free tier BTP account as well. In that BTP account, the subaccount I have been using for testing uses the `Subaccount Administrator` and `Subaccount Service Administrator` role collections. 

So, for a regular BTP account I would suspect that you would only need these two role collections and the  `Enterprise Messaging Administrator` role collection.

Hope that helps,
Alex

**Comment by ghost** [comment]
Hi Alex,

That really helps us. There is a question with the global account role level, as mentioned:

> The role collection I have for myself at the global account level is called Global Account Administrator. It contains the following roles: Global Account Admin, Global Account Usage Reporting Viewer, System Landscape Administrator, and User and Role Administrator.

Requesting the Global Account Admin role could be challenge for us (I would say) as it impacts to the entitlement management (cost); hence we always need to request to the authorized team. The question is after this command  for checking required btp services for use-case:

`btp --format json list accounts/entitlement --global-account 'a23c10d4trial-ga'`

As mentioned in the CLI command help page, it can be run with global account viewer role (https://help.sap.com/docs/btp/btp-cli-command-reference/btp-list-accounts-entitlement#ariaid-title4) 

Do we still need global-account role to execute any entitlement assignment? FYI, we're requesting role global-account-viewer and expect we can run the command.

Thank you,
Thien

**Comment by AFK-Python** [comment]
Hi Thien,

From my understanding, the global account viewer role is not needed to execute entitlement assignment, but global account admin is needed to execute entitlement assignment. Here are [the SAP Global Role Collection docs](https://help.sap.com/docs/btp/sap-business-technology-platform/role-collections-and-roles-in-global-accounts-directories-and-subaccounts#administrator-role-collections) for cross reference.

Please observe the description for the **global account viewer role**:

```
Includes read-only authorizations for viewing global account usage information.

The GlobalAccount_Usage_Reporting_Viewer role template provides this role. You find the role template in the SAP BTP Cockpit if you chose the uas!<suffix> application identifier
```

The purpose of this role in the tool is for validation checks in BTP. If this causes problems, our team can look into creating a docker image that circumvents this issue. 

Best,
Alex
