### ISSUE TITLE
Error: Updating service principal with object ID: "8ddb7d65-9945-4e22-8d0f-40f34194d252" MS Graph

### ISSUE THREAD

**Issue by ABVN-Huy** [SAP-samples/btp-bridge-framework#13]
Hi team,

I am Huy from ABeam, I am using terraform version.
After run ./btpsa I got error as below
![image](https://github.com/SAP-samples/btp-bridge-framework/assets/115139053/fabfcad9-9669-4413-812f-fe89e7a0b472)

I also found  in azure-ad-app/main.tf file these required roles
![image](https://github.com/SAP-samples/btp-bridge-framework/assets/115139053/79e59272-528d-4ec6-ab11-72551a38e3b1)

In Azure portal, I just guess that my account should be assign to MS Graph application and have above roles
![image](https://github.com/SAP-samples/btp-bridge-framework/assets/115139053/6038b9f8-461e-48f8-b4d8-6e77661bfa04)

![image](https://github.com/SAP-samples/btp-bridge-framework/assets/115139053/dfbbf038-1ba8-4198-b997-390c4372496e)

![image](https://github.com/SAP-samples/btp-bridge-framework/assets/115139053/207f93ec-376d-4e33-a6e1-47c7edaec476)

I am not sure about it as my Azure account is managed by admin team and I need to request. Do you have any advise or sample for Azure portal set up (screenshot is ok) ?

**Comment by viancu** [comment]
We were able to replicate the issue by removing the following roles: "Application Administrator" and "Global Administrator" (Directory Scope). 

For the current set up, these roles are required, but if obtaining these permissions is not possible, a manual approach might have to be followed. The documentation also contains the [manual steps here](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/manual-setup.md).

Hopefully this answers your question, but please let me know if I can provide further guidance.
