### ISSUE TITLE
unable to subscribe Azure-trial with E5 account

### ISSUE THREAD

**Issue by ghost** [SAP-samples/btp-bridge-framework#15]
Hi team,

This is a question on how we can subscribe to Azure trial with E5 account (follow the pre-req https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/prerequisites.md#signup-for-an-azure-free-trial-subscription).

Understood that when create sandbox for MS developer program E5, there is an admin:
![image](https://github.com/SAP-samples/btp-bridge-framework/assets/122419061/c6786436-1e61-4d9f-81c8-44741daf5191)

This admin account (i.e. tpham207@0mlnj.onmicrosoft.com) will have the teams admim to upload app and access the application teams-app.

Suggest that we use this account to subscribe Azure-trial in order to create Bot Service. However, I cannot use this account to subscribe:
![image](https://github.com/SAP-samples/btp-bridge-framework/assets/122419061/afce5567-f8b7-4a5e-9672-cd4ba7dede2e)

please help to look into and share hints for this step.

Thank you,
_Thien

**Comment by AFK-Python** [comment]
It's a little hard to say what might be going wrong here.

I would first rule out the following options:

<img width="867" alt="Screenshot 2023-06-08 at 11 25 29 AM" src="https://github.com/SAP-samples/btp-bridge-framework/assets/54761070/ff2f7a3d-0c28-440f-bd3e-003a1f7cb42f">

If it is still not working, it might be possible there is a current issue with E5 accounts and Azure subscriptions. If that is the case, another email should work for creating the Azure account, as long as you have Active Directory (AD) privileges. 

**Edit:** creating a new subscription should give you AD privileges by default.

Best,
Alex

**Comment by ghost** [comment]
Thanks Alex. I found no way to register.
