### ISSUE TITLE
Bot Configuration - Wrong Messaging endpoint

### ISSUE THREAD

**Issue by ghost** [SAP-samples/btp-bridge-framework#16]
Hi Alex:

* We are using the API endpoint https://api.cf.us10-001.hana.ondemand.com and able to run the automation tool successfully
* The backend app router after deployment: https://bridge-backend.cfapps.us10-001.hana.ondemand.com/
* But the bot configuration only updates with https://bridge-backend.cfapps.us10.hana.ondemand.com/api/messages (miss -001). Hence, the bot cannot show the card in the teams app.
* The same will apply for saml-scope in .env:
```
samlScope="api://bridge-frontend.cfapps.us10.hana.ondemand.com/botid-799ca7f1-6221-4498-b64d-b1b20eeee136/scp.access api://bridge-frontend.cfapps.us10.hana.ondemand.com/botid-799ca7f1-6221-4498-b64d-b1b20eeee136/access_as_user"
```
* The parameter.json as below for region and cfcliapihostregion
```
...
  "region": "us10",
...
  "cfcliapihostregion": "us10-001",
  "cfspacename": "dev",
```
Pls kindly advise. pls let me know if you need more info.

Thanks,
Thien

**Comment by ghost** [comment]
* Here is the error for samlscope

> error_description: 'AADSTS500011: The resource principal named api://bridge-frontend.cfapps.us10.hana.ondemand.com/botid-799ca7f1-6221-4498-b64d-b1b20eeee136 was not found in the tenant named 4de7fff9-ada9-4abd-abe5-7e536d083003. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\n' +

* this is extracted from backend application in BTP.

**Comment by AFK-Python** [comment]
Hi Thien,

The region in the samlScope value should be that of the `cfcliapihostregion`, not the `region` value. I just ran the automation tool and confirmed that it updates with the `cfcliapihostregion` - I could not repeat the error with the `region` value. 

Perhaps the parameter.json file or terraform code was modified for that run? Or maybe this is an old bot resource that hasn't been deleted? Either way, I'd recommend updating that value (by hand would be the fastest method, but you could run the terraform removal script and then re-provision the resources via terraform if you'd really like to).

Best,
Alex

**Comment by ghost** [comment]
Thanks, Alex.
In future, we will confirm again after running automation tool. 

BR,
Thien
