### ISSUE TITLE
ERR Attempting to retrieve destination from service binding

### ISSUE THREAD

**Issue by ghost** [SAP-samples/btp-bridge-framework#17]
* After deploy the solution succesfuly to BTP and Azure
* We manage to run the BridgeFramwork App in Teams. It keeps loading when we choose Purchase Order to display the object table.
* But it's unable to connect the back-end with following error log.
[teams-backend-2023-06-16 04_09_22.966+0000.txt](https://github.com/SAP-samples/btp-bridge-framework/files/11766186/teams-backend-2023-06-16.04_09_22.966%2B0000.txt)

* Here is just one we think it's the main cause
> 2023-06-16T04:08:40.947+0000 [APP/PROC/WEB/0] STDOUT {"custom_fields":{"messageContext":"destination-accessor-vcap","package":"core"},"level":"info","logger":"sap-cloud-sdk-logger","message":"Could not retrieve destination from service binding. If you are not using SAP Extension Factory, this information probably does not concern you. Unable to find a service binding for given name \"s4hanaonprem-destination\"! Found the following bindings: bridge-framework-destination, bridge-framework-connectivity, bridge-framework-xsuaa, bridge-framework-app-logger.\n      ","msg":"Could not retrieve destination from service binding. If you are not using SAP Extension Factory, this information probably does not concern you. Unable to find a service binding for given name \"s4hanaonprem-destination\"! Found the following bindings: bridge-framework-destination, bridge-framework-connectivity, bridge-framework-xsuaa, bridge-framework-app-logger.\n      ","timestamp":"2023-06-16T04:08:40.947Z","written_at":"2023-06-16T04:08:40.947Z","written_ts":1686888520947}

Is there a way to troubleshoot this issue or any hints to solve it. Please advise.

Thank you.
Thien

**Comment by ghost** [comment]
* We are able to run the request and display PO
* We checked SAML SSO claim attribute and maintain ```emailaddress``` for Azure user then it can authenticate and get service.
* If that is not the way pls suggest.

Thanks,
Thien

**Comment by AFK-Python** [comment]
Hi Thien,

Can you clarify this point for me:

```
We checked SAML SSO claim attribute and maintain emailaddress for Azure user then it can authenticate and get service.
```

There's a couple of things that could occur that could cause this load error. One is that the certificate that configures the trust b/w BTP and Azure is invalid. Another is that emails are not listed in BTP or the appropriate resources in Azure - which is what I think you meant by the email address point that I am seeking clarification for.

Best,
Alex

**Comment by ghost** [comment]
Hi Alex:
* The certificates are exchanged automatically between Azure and BTP during the automation run, and it's not our issue.
* The finding was that the email address attribute in my Azure User profile was missing the email created automatically for Azure Trust in BTP.
* We also set up the principal propagation between BTP and S/4HANA via CN=$email.
* Teams can connect and display the PO data after maintaining the email. Hence, it is believed email in Azure AD is our root cause.
