### ISSUE TITLE
Possibility to rollout the scenario

### ISSUE THREAD

**Issue by ghost** [SAP-samples/btp-bridge-framework#18]
Hi Alex,

As the terraform docker images, we can see there are two scenarios:
* Purchase Order - configured as a sample - runs perfectly now in our environments.
* SalesOrder - not configured yet

We seek advice on how to roll out Purchase orders to other business objects. Our target is Purchase requisition and Purchase requisition flexible workflow at the item level. We understand that to roll out new business objects, we have to config the landing page, object page, table page, and so on. Therefore, the questions are:
* what is the best way to do that?
* Can we configure any objects which expose as OData service? or is there any restriction for the current version?

Thanks,
Thien

**Comment by AFK-Python** [comment]
Hi Thien,

Regarding your configuration of other objects question, you should be able to configure any business object exposed as OData, so long as the API is provided by the supported LoB (S4 Hana [on cloud or prem], Graph, ISuite). Docs on the OData API can be found [here](https://api.sap.com/content-type/API/apis/packages).

In terms of setting up business objects, I would reference [this documentation](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/config/Bridge%20Application%20JSON%20Configuration.md), specifically [this](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/config/Frontend%20Config.md) for the frontend*.

I will also see if I can provide you with something better, but for now that reference is probably the best one. My team and I are also happy to address any specific questions or problems you run into during setup, please feel free to raise any issues for problems that come up.

**Note:** some of the components in the frontend documentation may not work as expected, some are in beta - we apologize for this and will be updating our documentation on the next round of updates to the repo.

Best,
Alex

**Comment by ghost** [comment]
Hi Alex,

Glad to see the possibility of scaling the application. We have been working with SAP Netweaver OData, and we can understand the setup for OData API.

I will close the issue now and will open new one if we hit any problem.

Thank you,
Thien
