### ISSUE TITLE
Purchase Order Approval Decision

### ISSUE THREAD

**Issue by ghost** [SAP-samples/btp-bridge-framework#19]
Hi Alex,

We set up a flexible workflow for PO in S/4HANA on-premise. We activate /IWPGW/TASKPROCESSING gateway service. But while displaying Teams card, the approval/reject button (we guest so) does not display.
Can you share us the information of how workflow work in the Teams app.

Thanks,
Thien

**Comment by I561660** [comment]
> Hi Alex,
> 
> We set up a flexible workflow for PO in S/4HANA on-premise. We activate /IWPGW/TASKPROCESSING gateway service. But while displaying Teams card, the approval/reject button (we guest so) does not display. Can you share us the information of how workflow work in the Teams app.
> 
> Thanks, Thien

Hi Thien good morning. This purchase order approval functionality is one of the use cases we built on top of the bridge framework.  In order to receive the notification card for the purchase order approval, we needs to add additional configurations on the bridge framework config server, and also schedule an ABAP job in the SAP S/4HANA On-Prem system. 

Please kindly follow the instructions in this [discovery center mission](https://discovery-center.cloud.sap/missiondetail/4164/4408/) to have everything up and running.

Best Regards,
Weikun Liu

**Comment by ghost** [comment]
Hi Weikun,

Thanks for the good hints. We can implement the push notification from S/4HANA to Teams by Event mesh. Great to have the mission in the discovery center to follow.

But there comes a concern arises:
* After approval, the adaptive card information is updated:
![image](https://github.com/SAP-samples/btp-bridge-framework/assets/122419061/e4df2eb8-99bc-4908-806e-fa896cdf2a5b)
* View the detail again; the button approve and reject still display
![image](https://github.com/SAP-samples/btp-bridge-framework/assets/122419061/9792448c-bf79-4afc-953c-d51d633401cd)

We expect the app should display the status of the purchase order already approve as sample https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/config/Bridge%20Application%20JSON%20Configuration.md

Are we missing any step.

Thank you,
Thien

**Comment by AFK-Python** [comment]
Hi Thien,

Apologies for the delay, we are looking into this unexpected behavior now, and will get back to you as soon as we can.

Best,
Alex

**Comment by AFK-Python** [comment]
Hi Thien,

We found a bug in the code. Please update lines 117-136 of `/frontend/src/components/ObjectPage.jsx` with the following code:

```
            // Setting creation date
            if (data.hasOwnProperty(props.config.CreationDate)) {
              const date = helper.formatDate(
                JSON.parse(JSON.stringify(data[props.config.CreationDate]))
              );
              setCreationDate(date);
            }

            // Date on which order was last changed, including status changes
            if (data.hasOwnProperty(props.config.LastChangeDateTime)) {
              const date = helper.formatDate(
                JSON.stringify(data[props.config.LastChangeDateTime])
              );
              setLastChangeDateTime(date);
            }

            // Status whether order is approved, rejected, or pending
            if (data.hasOwnProperty(props.config.PurchasingProcessingStatus)) {
              setStatus(data[props.config.PurchasingProcessingStatus]);
            }
```

Once again, don't forget to build and then push your frontend! We will be including this in the next round of updates for Bridge. 

Best,
Alex
