### ISSUE TITLE
Login to BTP account error

### ISSUE THREAD

**Issue by LyubomirDenkovAct** [SAP-samples/btp-bridge-framework#23]
Hello 
I receive error when trying to log into BTP account (from docker container) while I followed automation setup guide, all configuration which are described in guide are done correct, but still receiving an login error. 

Log file: [Logs.md](https://github.com/SAP-samples/btp-bridge-framework/files/12036934/Logs.md)

Parameters in log which are HIDED are correct set (by following guide) and I can provide them if needed.

Best regards
L. Denkov

**Comment by AFK-Python** [comment]
Hi,

First, I want make sure the correct value was used for login. A clarifying note about the subdomain parameter used in the btp login command, it is actually the `globalaccount` account value in your parameter.json file.

To set the `globalaccount` value in your parameter.json, please navigate to your global account settings (gear icon in the top right hand corner of your global account) -> General Page of the global account settings -> Global Account Subdomain. Copy the Global Account Subdomain value and paste it in parameters.json for the `globalaccount`.

Next, I would like to confirm that the login process was attempted successfully. When running the pipeline, the login command should look something like this:

```
[2023-07-13 21:48:12] INFO       : Logging-in to your global account with subdomain ID >subdomain_value<
[2023-07-13 21:48:12] RUN COMMAND: btp login --url 'https://cpcli.cf.eu10.hana.ondemand.com' --subdomain 'subdomain_value' --sso
Connecting to CLI server at https://cpcli.cf.eu10.hana.ondemand.com...

Opening browser for authentication at: <auth_link>

Failed to open browser. Please authenticate manually.
Waiting for user authentication to complete (use Ctrl+C to abort)...
```

I did not see a browser link appear for you - which makes me think this was a connection or timeout issue - but the authentication link must be manually clicked on. From there you will need to press the button `Yes, login to SAP BTP` to complete authentication.

I usually see this error if no action is taken on the authentication link for approximately 2 minutes.

If the problem remains unresolved after all of this, please try running the command `btp login --url 'https://cpcli.cf.eu10.hana.ondemand.com' --subdomain '<subdomain_value>' --sso` (**recall that the subdomain value is actually the global account subdomain value!**). If the command is working, it should then work on a re-trigger of the pipeline. If it fails, please paste the output of the command from the terminal.

Best,
Alex

**Comment by AFK-Python** [comment]
Also, it is possible your docker setup automatically redirects these types of links to the browser, so that might be something to keep an eye on.

**Comment by LyubomirDenkovAct** [comment]
Hello

I tried from 2 machines, from first I still get that error, but from second machine I have succeeded operation (login to btp account).
do you have any suggestions what can be the problem from the first machine? Maybe any security/user restrictions or something else?

Best regards
L.Denkov

**Comment by AFK-Python** [comment]
Hi,

What type of machine is it? Hopefully, I'll be able to better assist you with some more details.

We have had issues with apple silicon chips and the docker container in the past, specifically M1 machines; however this specific error has not appeared before in our testing.

The docker container is also mainly intended for those running it on windows or mac, but it should (theoretically) work for other unix based systems.

Best,
Alex

**Comment by LyubomirDenkovAct** [comment]
Hello

We are continue investigating the problem but for now we think it's from company policy which is blocking connection operation (like BTP login) from container. I'll write other comment when we have clear vision what is the problem and how we solved it. 

Best,
L.Denkov
