### ISSUE TITLE
Error while deploying backend application to BTP

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#24]
Hi,

I am getting following error while deploying the backend application to BTP via manual set up.

```
   2023-08-01T10:28:26.65+0000 [APP/PROC/WEB/0] ERR npm notice New minor version of npm available! 9.5.1 -> 9.8.1
   2023-08-01T10:28:26.65+0000 [APP/PROC/WEB/0] ERR npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
   2023-08-01T10:28:26.65+0000 [APP/PROC/WEB/0] ERR npm notice Run `npm install -g npm@9.8.1` to update!
```

I have checked the node version and it is 9.8.1 in package-lock.json. Could you please suggest what could be the issue.

Thanks,
Chanchal

**Comment by ChanchalAgrawalMiku** [comment]
Hi, 

I have fixed the error by adding engine manually in package.json file.

```
"engines" : { 
    "npm" : "^9.8.1" 
  }
```

but now getting a [new error as mentioned in this issue](https://github.com/SAP-samples/btp-bridge-framework/issues/27). Please suggest what could be the issue with this new error of invalid_type at connectionString and containerName.

  ```
Issue #0: invalid_type at connectionString
  Required

  Issue #1: invalid_type at containerName
  Required
```

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Was there more to the error message above? It strikes me as strange that the backend would not work with a slightly older version, especially since I can get it to run with npm version `8.17.0`.

I'll address the new error in the other issue, shortly.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Thanks.
