### ISSUE TITLE
Azure initial setup issue

### ISSUE THREAD

**Issue by Backo123** [SAP-samples/btp-bridge-framework#25]
Hello Bridge Framework team,

I am facing an issue while following the prerequisites guide for MS Dev account and Azure free trial subscription - https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/prerequisites.md#signup-for-an-azure-free-trial-subscription. When I try to login with the MS Dev account created on the previous step I get the following message:
![изображение](https://github.com/SAP-samples/btp-bridge-framework/assets/140487803/664c2220-0b6c-4adb-9e20-36c17c1477a9)
I know there is little you can do about it, but I just want to let you and other users know about this setback.

Best Regards
Vassil

**Comment by AFK-Python** [comment]
Hi Vassil,

Thanks for raising the issue. Note, you should still be able to continue with Bridge, you just need to sign up for Azure and ensure that you have access to Azure AD (active directory) -  a different email should work. This should be possible even in free tier accounts.

If that still does not work, please let us know!

Best,
Alex

**Comment by Backo123** [comment]
Hello Alex,

Thanks for the answer.

I see I didn't explained well. I get the message as soon as I click "Start free". How could I continue as I can not sign in for Azure and thus have an Active Directory access?

Best Regards
Vassil

**Comment by AFK-Python** [comment]
Hi Vassil,

Is this message coming from an account related to your organization? More specifically, is the email behind the Microsoft account an organizational email? This can cause problems as some organization emails are unable to be used for Azure accounts. Creating a new Microsoft account with an email unrelated to the organization should allow you to start the Azure free tier. 

If the message persists on a different email, please let us know. If you already are using a personal email, I would try a different one once more. It's possible the same issue that causes some organizational emails to be blocked from using Azure  is occurring here.

Best,
Alex
