### ISSUE TITLE
Link to Docker image not found

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#26]
Hi,

For automated set up, please provide the link to docker image.

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

You can find all of our docker images under our [release page](https://github.com/SAP-samples/btp-bridge-framework/releases). I would recommend using the terraform version, if your system can.

Please let us know if you need any further help with the docker image!

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Thank you.
