### ISSUE TITLE
which URL to configure in SAP Integration Suite iflow to send data to teams

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#28]
Hi,

I have now deployed the app in BTP and Teams successfully. I have extended the use case so that sales order data will be sent from S/4HANA via SAP Integration Suite to Teams. So please suggest which URL should I enter in Integration Suite iFlow (at receiver adapter) so that it will send the data to Teams. Is it BTP bridge-framework-frontend app url or bridge-framework-backend app url?

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

This url comes from the integration suite artifact. You can navigate to integration suite from your BTP subaccount -> Instances and Subscriptions -> Integration Suite.

Once inside of the integration suite portal, navigate to IFlow artifact. For example Design (side bar in integration suite) -> Integrations -> select your system -> Artifacts -> select your artifact. From here, deploy the artifact (confirm any prompts that ask for deployment confirmation).

After deployment, go to Monitor (side bar in integration suite) -> Integrations -> All. From here you should see details about what was just deployed. Select the artifact that just deployed and it should list the endpoint needed for the URL value. If the artifact does not have an endpoint yet, you may need to re-deploy or see the "valuehelp" options for the endpoint. 

**Note, the url should be truncated after the `.com` portion as the rest of the path should be configured in the objectMappingConfig.json file in the backend.**

If you are in need of help for creating/developing an IFlow, need more details about this problem, or want more information about the objectMappingConfig.json file, please let us know and we can point you in the right direction with some documentation.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi,

I want to send the sales order CREATED data as a notification to teams via integration suite iflow (and do not want to get or search or update sales order data from teams). so which URL I need to enter in receiver adapter in iflow to send the sales order created data to teams?

Please share the link to the end-to-end testing steps of the bridge framework?

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

The URL needed for the receiver adapter should be the endpoint related to your S4 tenant, adapted with the sales order path details.

Additionally, [this configuration guide](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/config/Backend%20Config.md) on the backend might be useful. It displays an example of an IFlow connection.

Regarding end-to-end testing, are you looking for how to get the app up and running successfully? I would recommend going over the [manual setup guide](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/manual-setup.md), specifically [step 4](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/app-deployment/manual-deployment.md).

Best,
Alex
