### ISSUE TITLE
frontend app url ended up with HTTP 403 Forbidden error

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#29]
Hi,

I have deployed the bridge-framework-frontend app in BTP but when url is opened then it is showing HTTP 403 forbidden nginx error. In cf logs, it is throwing the following error logs. Please suggest what could be the issue.

`2023-08-02T19:49:40.02+0000 [APP/PROC/WEB/0] ERR 2023/08/02 19:49:40 [error] 69#0: *9 directory index of "/home/vcap/app/public/" is forbidden, client: 10.129.175.239, server: localhost, request: "GET / HTTP/1.1", host: "bridge-framework-frontend.cfapps.eu10-004.hana.ondemand.com"`

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

We suspect this error is coming from just pushing the frontend application to Cloud Foundry. The frontend must first be built and then pushed.

We recommend using the `build-and-push.sh` script in the frontend folder - it will handle the build and push for you.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi,

Yes, I have run "./build-and-push.sh" command but it is still failing with HTTP 403 error. Do we need to run "npm install" (before  ./build-and-push.sh) in frontend as well?

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Yes, you must run `npm install` before building and deploying. This is needed in order to grab all of the dependencies needed for the frontend to run.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

I run "npm install" and then run "./build-and-push.sh" but it is failing with following error. Please suggest what went wrong. 

```
> bridge-framework-frontend@1.0.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'path' in '/home/user/projects/btp-bridge-framework/frontend/node_modules/dotenv/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
```

Br,
Chanchal

**Comment by ChanchalAgrawalMiku** [comment]
Hi, 

I have now fixed the above issue by running "yarn" command and have pushed it to CF. However, the frontend url is opening a blank page (with React App). Please suggest what kind of web page should be opened in frontend url ?

Br,
Chanchal

**Comment by ChanchalAgrawalMiku** [comment]
Hi,

Please suggest what kind of web page should be opened in frontend url ?

Br,
Madan

**Comment by AFK-Python** [comment]
Hi,

Apologies from the delay on my side. I haven't had a chance to explore the `npm install` issue, but it generally isn't a good idea to mix and match `npm` and `yarn`. I guess if it works, let it be, but if you wanted to look into it further the `npm install` + the build-and-push script failure, it seems like a local environment issue.

Regarding the second question, I'm a little confused by the nature of the question. However, opening the url tied to the frontend (i.e. opening the application route value in BTP) will lead to a forever loading page. The frontend is meant to be viewed through teams.

I suggest looking through [part 2](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/app-deployment/ms-app-deployment.md) of the [manual setup guide for application deployment](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/app-deployment/manual-deployment.md). This part of the documentation will walk you through how to upload the application to teams, and what is should look like in teams - the latter seems more useful to your second question.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi,

Thanks. I have deployed the teams application and bot. In teams app, it is showing as following but when clicked "Get Started", it opens up a pop-up but pop-up page is a blank page. Should there be a list of context when we click "Get Started" in teams app?

```
Hi there! Welcome to the Bridge Framework.

This read-only bot is your personal space to receive notifications from SAP.
You can launch Bridge Framework from the list of messaging extensions in any of your chats.

Key Features:

Bring SAP business objects into Teams for collaboration.
Bring SAP approval workflows into Teams.

Get started:

To take a quick peek, use Get Started button below.

Get Started <has context menu>
```

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

There should be a list of tile(s) appearing if everything is working.

Do you get an error message in the pop-up? Something like: `Unable to reach app. Please try again.`?

Other possibilities that might help me figure out what might be going wrong:
 - is the frontend .env configured?
 - how much of the backend .env is configured?
 - has your `config/public/frontend/landingPageConfig.json` been modified from the default version?
 - are your Azure resources working properly? (I'll create a follow up reply on this)
 - double check BTP space to make sure the frontend, config and backend applications are all running without any problems
 - **(this would be after the landing page render something)** it seems like you were trying to implement Bridge for sales orders, has the resulting configuration been updated for the frontend? you would need to add json files to the integration suite corresponding to your sap system (i.e. see the purchase order example with `/config/public/frontend/simpleConfig/S4HanaOnPrem/IntegrationSuite/PurchaseOrder*.json`)

Best,
Alex

**Comment by AFK-Python** [comment]
Follow up on Azure resources

**Bot checks:**
 - Go back to the configuration of the bot, specifically the OAuth connection setting that has been created. Click on it. At the top right of the side panel that just opened, select 'Test Connection'. If everything is working you should receive a token.
 - Go back to the bot, but instead of configuration, select 'Test in Web Chat'. If everything is working you should see the Bridge welcome card being delivered.

**Enterprise Checks:**
 - Navigate back to the saml sso page of the enterprise application. There should be a 'Test this application' button at the top. Click on it and then click 'Test sign in' on the newly opened panel. If everything is working you should be redirected to a page where you are logged in with your email.

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

Yes, I am getting this error in pop-up. `Unable to reach app. Please try again.`

Azure set up and bot set up are ok. 
Bot checks: test successful in both OAuth and web chat
Enterprise Checks: test successful

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

That error message usually means there are issues with how the Azure resources were created, specifically the bot. However, to be able to better help you, it would be good to know the answer to those questions. I would also check the health of the channels of the Azure bot, please let me know if MS Teams is affected. Channels are in the same side panel as configuration.

At this point I would also like to bring up that it might be easier to pivot to the automated setup via the docker container, as debugging by hand can be tedious and difficult. Even if automated setup errors, it usually is easier to fix problems that occur there.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

yes, 

- is the frontend .env configured?
- > yes, frontend .env is configured with config and backend url

- how much of the backend .env is configured?
- > backend .env is also up-to-date now. saml was remaining, which I have updated as suggested. transcript is kept as it is, but will not be using much the transcript.

- has your config/public/frontend/landingPageConfig.json been modified from the default version?
- > No, it is same as it is.

- are your Azure resources working properly? (I'll create a follow up reply on this)
- > yes, tested and working correctly

- double check BTP space to make sure the frontend, config and backend applications are all running without any problems
- > yes, all 3 apps are running and healthy in BTP

- (this would be after the landing page render something) it seems like you were trying to implement Bridge for sales orders, has the resulting configuration been updated for the frontend? you would need to add json files to the integration suite corresponding to your sap system (i.e. see the purchase order example with /config/public/frontend/simpleConfig/S4HanaOnPrem/IntegrationSuite/PurchaseOrder*.json)
- > I am testing also with purchase order along with sales order. but I have not changed any json file in config ( PurchaseOrder*.json and SalesOrder*.json are as it is). I have configured the required 6 integration flows in CPI for both purchase order (get, search, update) and sales order (get, serach, update).


Br,
Chanchal

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

Yes, channels in Bots are affected. 

Microsoft teams - Issue (1)
Web Chat - Issue (4)

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

This occasionally happens, it seems to be an issue on the Azure side of things.

There are two options here:
 1. Delete the MSTeams channel (web chat should not matter) and then re-enable it
 2. Delete the Azure Bot and re-create one

Option 1 rarely works but, if it does, would make life much easier, as it is much simpler to do. Option 2 will work, but it is a pain as it will require resetting other Azure apps as well - anything tied to the bot would need to be reset as well.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

Thanks. I re-created channel and also Bot. Also updated everywhere. but the error is still the same. I checked the logs in BTP backend app. Request is reaching to BTP backend app with end point as "/api/messages" with HTTP 200 but task list is not being sent back to Microsoft Teams. Can you please update what could be the issue in backend app to fetch the task list with end point "/api/messages". 

is it taking a lot of time to send the response from BTP, so it is failing in Teams?

Logs of backend application:
```

   2023-08-07T13:07:38.48+0000 [APP/PROC/WEB/0] OUT goToUrl: 'https://bridge-framework-frontend.cfapps.eu10-004.hana.ondemand.com',
   2023-08-07T13:07:38.48+0000 [APP/PROC/WEB/0] OUT type: 'task/fetch'
   2023-08-07T13:07:38.49+0000 [RTR/0] OUT bridge-framework-backend: POST /api/messages HTTP/1.1" 200 1288 260


    "component_name": "bridge-framework-backend",
    "component_type": "application",
    "direction": "IN",
    "layer": "[NODEJS]",
    "level": "info",
    "logger": "nodejs-logger",
    "method": "POST",
    "protocol": "HTTP/1.1",
    "request": "/api/messages",
    "response_size_b": -1,
    "response_status": 200,
    "response_time_ms": 1660,
    "source_instance": 0,
    "type": "request"
```

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

There's a few things that might be going wrong here, but the two most likely are:
 1. Bot id is not updated everywhere
 2. If the only resource that was changed was the bot, I do not believe it can be reconnected to the original application registration

For option 1, please double check that the bot id has been updated in the manifest.json, backend .env file, and across resources in Azure.

See [here](https://github.com/SAP-samples/btp-bridge-framework/blob/main/teams-app-package/manifest.json) for the locations that need to be updated for the manifest.json.

For the backend .env file, you may need to update the `MicrosoftAppId` - this depends on how you were able to recreate the bot (i.e. if it was new, tied to the existing application registration, or something else). The samlScope will also need to be updated, as the uris describing the roles contained the bot id.

In Azure there are a few places the bot id is used and would need to be updated. The bot's configuration OAuth settings would need to be double checked, as the scopes of the OAuth setting use the bot id. Additionally, the application registration tied to the bot uses the bot id in the application id uri, as well as the redirect uris (these can be found under the 'Authentication' tab, under 'Manage' in the left side panel).

If all of these values have already been updated, then it seems like a connection issue b/w the backend and teams, which seems to suggest something went wrong with the bot resource. Although, it might be possible something is going wrong in event mesh, it's hard to say with a 200 status code. Alternatively, if the bot was not recreated with a new application registration this would be the problem. Our testing has found that the bot needs to be tied to an application registration to work, and that connection seems to only work on instantiation of the bot.

If the current behavior continues after doubling checking all of the bot ids, **I would strongly recommend switching to using automated setup**. Connections are far less likely to go wrong when using the docker container for setup. Additionally, errors in setup tend to be far easier to fix. Furthermore, after setting up the configuration files in the Docker container, the rest of the setup for resources should take around 10-15 minutes. You would need to copy in your config files to take into account the sales order case you are working with.

Note, I will continue to assist you should you need further help with manual setup, but, once again, if this behavior persists, I would switch to using the automated setup tool.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex, 

Yes, I have recreated all in Azure (application, Bot, OAuth, Storage, etc). and I have updated the new bot and extension application details in .env file of backend app and manifest file of teams app as well. 

I will proceed with automated set up but would like to understand few last things before that. 

1. I have currently E3 license in Teams and Azure. is E5 license mandatory for this?
2. just to double check all parameters of backend .env file --> please provide where all I can find the values of each parameter in the backend .env file. 

Thanks,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Regarding the first question, it should not matter so long as you have access to Azure Active Directory and can provision resources in Azure. I do not believe the E3 license will hinder either of these privileges, but sometimes company email Azure accounts are restricted and you may need to use your personal email to create an Azure account without restrictions.

I will follow up with a second post regarding the backend .env file.

Best,
Alex

**Comment by AFK-Python** [comment]
Following up, here is all of the information tied to the .env file with comments on where to find the value:

The `MicrsoftAppId` is the value of the application id of the application registration tied to the bot. This can be found on the overview page of the application registration.

The `MicrosoftAppPassword` comes from the client secret value that is tied the application registration. This is under the 'Certificates & secrets' section of the application registration.

The `connectionName` is the name of the OAuth connection setting that is configured in the bot service. It is under the configuration tab.

The `MicrosoftTenantId` is the tenant id of the Azure AD account. This value can be found under 'Basic information', after navigating to the Azure Active Directory page (either by locating this in the left side bar or searching for it).

The `xsuaaClientId` the client id value of the same xsuaa instance from which the `samlResourceUrl` is grabbed from. It is located next to that url value, see the explanation for the `samlResourceUrl` for more info.

The `xsuaaClientSecret` the client secret value of the same xsuaa instance from which the `samlResourceUrl` is grabbed from. It is located next to that url value, see the explanation for the `samlResourceUrl` for more info.

The `frontendUrl` should be set to the value of the frontend url. This should look something like this: `https://<frontend_name_used>.cfapps.<cloud_foundry_api_region>.hana.ondemand.com/`.

The `frontendFallbackUrl` is the same as the `frontendUrl`.

The `samlScope` comes from the bot's OAuth connection settings scope value. This can be found by navigating to the bot created, selecting 'Configuration' (under 'Settings') from the left side bar, and clicking on the OAuth connection that was created. In the right side bar that opens, the scopes string is the value of the samlScope.

The `samlResourceUrl` comes from xsuaa service with the application plan in BTP. You can search for this in your subaccount under 'Instances and Subscriptions'. After clicking on the xsuaa instance, a side panel should open up with more details about it. In this side panel, select 'View Credentials'. The first url value in the JSON is value of the samlResourceUrl.

The `samlAlias` can be found under the enterprise application. After navigating to the enterprise application, click on the link next to Managed application in local directory. On the page that opens up, select 'Single sign-on' (under 'Manage') from the left side bar. The samlAlias is the value that comes after the /alias portion of the logout and reply urls.

The `configServerUrl` should be set to the url of your config server app. This should be defined in the manifest.yaml file used to push the config server. The url should look like this: `https://<name_used>.cfapps.<cloud_foundry_api_region>.hana.ondemand.com/`.

The `REACT_APP_SCROLL_PAGE_SIZE` is any integer value under `500`, we typically set this value to `400`.

The `cacheTTL` is preconfigured to `300` already.

The `TranscriptSummaryEnabled` is set to true by default to `true`. This will enable transcript summary generation after every teams meeting. This should be set to `false` if the transcript summary feature of Bridge is not being used.

The `UserId` should be set to the `Object ID` of the user. To find this value, please see the section ('Gather information from Azure Portal')[https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/transcript/Transcript%20Set%20Up.md#gather-information-from-azure-portal] of the (Transcript Set Up guide)[https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/transcript/Transcript%20Set%20Up.md].

The `GraphApiEndpoint` is set by default to `https://graph.microsoft.com/beta`.

The `TranscriptSummaryModelEndpoint` is set to `https://api-inference.huggingface.co/models/knkarthick/MEETING_SUMMARY` by default. This can be changed to the url value of a different model on Hugging Face, but this may require adaptations to the `backend/helpers/transcriptSummary.js` file.

The `TranscriptSummaryModelAPIKey` is set to the API key from Hugging Face. To grab this value, please see the section ('Update Your Backend .env File With the Necessary Information')[https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/transcript/Transcript%20Set%20Up.md#update-your-backend-env-file-with-the-necessary-information] of the (Transcript Set Up guide)[https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/transcript/Transcript%20Set%20Up.md].

Any of the transcript values (`TranscriptSummaryEnabled`, `UserId`, `GraphApiEndpoint`, `TranscriptSummaryModelEndpoint`, and `TranscriptSummaryModelAPIKey`) can be omitted if you do not want to use the transcript summary feature.

I will follow up with the remaining 5 fields later, as I need to spin up an instance to double check their values and how to grab them.

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

Thank you. .env file is updated correctly by me as suggested above. I will proceed with automated set up now.

After I click "Get Started" in welcome page of MS-teams app bot, then it is trying to fetch the tasks from SAP BTP backend app (with successful HTTP 200 response). **Where are the tasks maintained in SAP BTP?** (which needs to be sent back from SAP BTP to MS-Teams)?

Can you please provide some screenshots of how the app in teams will look like at different stages (like task list, initial list, before approval, after approval, etc)

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Sorry for the delay on my side, but here are the remaining .env values you may need:

`graphClientId` and `graphClientSecret` both come from the credentials of the graph service, similar to the `xsuaaClientId` and `xsuaaClientSecret`.

The `iFlowClientId` and `iFlowClientSecret` are found as such:

 1. Create a Process Integration Runtime instance in the subaccount with the Integration Suite application
 2. Once the instance is up and running, create a Service Key.
 3. Use the key's client and secret credentials as basic auth to call the endpoint with a `grant_type=client_credentials` parameter in order to fetch the bearer token.
 4. Then the iflow endpoints should be callable with the returned bearer token.
 
The iflow endpoints can be found in `Integration Suite > Monitor > Integrations > Manage Integration Content > All`. The `iFlowUrl` endpoint should be found here.

I will follow up with images at different stages of the app, specifically for purchase orders, please let me know if you'd like to see a different use case.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex, 

Thank you. Purchase order images would be fine. I have one below query.

- When I click "Get Started" in welcome page of MS-teams app bot, then it is trying to fetch the tasks from SAP BTP backend app. Where are the tasks maintained in SAP BTP? 

It seems "Get Started" in MS-Teams app is showing the for-ever loading page (same as of BTP frontend url) so would be good to check: where are the task list in BTP?

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Regarding the images, please reference this [README](https://github.com/SAP-samples/s4hana-microsoft-team-app-integration/tree/mission/E2E%20Testing). I believe this should have everything you need for what the app looks like.

Regarding the tasks question, I'm a bit confused, perhaps you could elaborate on what you mean by this? Bridge is mainly intended to share business objects between users and allow them to accept/reject business objects, when applicable and enabled. As a result, I'm confused by the task list question. You should be able to view all of and search for the business objects.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

I am not able to view all of and search for the business objects. It is showing only the blank page.

I checked the images in given link. So as soon as the purchase order was created in S/4HANA (manually), then event notification was sent automatically to MS-Teams App bot. so this is happening with which of the below approach?

- S/4HANA --> Event Mesh --> backend App --> MS-Teams 
> -If this is the right approach to send the purchase order notification, then where do we need to configure the Event Mesh details in BTP App?  

- S/4HANA --> Event Mesh --> Integration Suite --> backend App --> MS-Teams 
> -If this is the right approach then integration suite will read the queues from event mesh and then will send it to BTP App. Which URL needs to be configured in iflow receiver adater pointing to BTP App?

Thanks,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

The first flow `S/4HANA --> Event Mesh --> backend App --> MS-Teams` is correct.

For the details regarding the setup of Event Mesh standard, the default plan service instance, and the message queue, please see the docs below:
 1. [Subscribe to Event Mesh User Interface on SAP BTP](https://help.sap.com/docs/SAP_EM/bf82e6b26456494cbdd197057c09979f/83777b586ec54a01b5e807620f5c4660.html)
 2. [Create a  Event Mesh Default Plan Instance](https://help.sap.com/docs/SAP_EM/bf82e6b26456494cbdd197057c09979f/d46ce54abd094c5caf38a71275b3e600.html)
 3. [Create a new MQ in the Event Mesh Messaging Client](https://help.sap.com/docs/SAP_EM/bf82e6b26456494cbdd197057c09979f/57af1bd4e8f54b0a9b36414a5ec6b800.html?q=messahe%20queue)

However, if you went ahead with automated setup, this should already be set up for you, and the problem may lie elsewhere.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

yes, I have already created all of these for Event Mesh. but I wanted to know: 

1. where are we configuring to consume the queues from event mesh in backend app?  
2. in teams manifest.json, what values do we need to enter in parameters name and title (is it param only)?
  
> ```
>       "parameters": [
>             {
>               "name": "param",
>               "title": "param",
>               "description": ""
>             }
>           ]
> ```

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

You will need to setup the Event Mesh default plan instance, in-order to create the messaging client in the Event Mesh UI. The default.json file from the automation pipeline already configures this for you. If you need the details by hand, refer to the code below (from default.json) for values to create and configure the queues:

```
{
        "category": "SERVICE",
        "name": "enterprise-messaging",
        "plan": "default",
        "amount": 1,
        "instancename": <enter instance name>,
        "createServiceKeys": [<service_key_name>],
        "parameters": {
          "emname": <some name>,
          "namespace": "orgName/<emname>/uuid",
          "version": "1.1.0",
          "options": {
            "management": true,
            "messagingrest": true,
            "messaging": true
          },
          "rules": {
            "queueRules": {
              "publishFilter": ["${namespace}/*"],
              "subscribeFilter": ["${namespace}/*"]
            },
            "topicRules": {
              "publishFilter": ["${namespace}/*"],
              "subscribeFilter": ["${namespace}/*"]
            }
          }
        }
      }
```

Regarding the second question, the manifest.json file has no correspondence to BTP. The manifest.yml file does let you specify the BTP services the app needs to use, if that is what you mean.

Once again, I suggest you use the automation pipeline instead of manual setup, and then add the changes needed for you specific use case. Your issues related to Azure and Event Mesh would've been solved already.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi,

All set up now working fine without any error. But I still did not find the configuration in BTP extension app to read the queues from event mesh. Can you please update on this?

br,
Chanchal

**Comment by ChanchalAgrawalMiku** [comment]
Hi,

Please suggest if it is possible for us to have a call?

Because everything is set up but something is still missing. 
1. when I am creating purchase order, it is reaching event mesh queues but not in microsoft teams. Can you please share the output format of ABAP job (the data format which S/4HANA sends it to event mesh via ABAP Job).
3. when I am clicking on "Get Started" in microsoft teams, then a blank page is showing (and no task list). Why the landing page is not showing?

<img width="349" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/58e4dedb-61d1-4658-bf71-c30b536e0631">

<img width="479" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/834de4a9-2b24-408a-8c60-2e017102eaa8">


Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Let me check with my team to see if we can schedule a call - it is not something we typically do for issues on samples.

Regarding the first question in the backend there is a method with the name `notificationRouter.post("/notifyUser", async (req, res))` in the `NotificationRouter.js` file. This serves as the message queue consumer, and the api endpoint would be `/notify/notifyUser`.

Note, this method does not explicitly subscribe to the message queue in the event mesh programmatically. Instead, we are using the Event Mesh message queue web hook functionality. The web hook functionality allows the message queue to send the message to the `/notify/notifyUser` endpoint.

In the `parameter.json` file - which can be found in the docker container - there is a section that handles the web hook creation:

```
"queueCreation": {
      "subscription_name": "bridge-subscription",
      "queue_name": "orgName/automationEventMeshTestEMName/uuid/test3"
    }
```

All of this can be configured and seen in the event mesh UI. Are you able to enter the event mesh UI? This should be possible by clicking on the event mesh instance at the subaccount level. Please check this, and if everything here is correct on your side, I will look into the ABAP job.

As for question number 2, what does your `landingPageConfig.json` look like? It should be something like [this](https://github.com/SAP-samples/btp-bridge-framework/blob/main/config/public/frontend/landingPageConfig.json). If you are able to get to the get started button, then if the landing page json file is correctly configured, it should appear.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi Alex,

Thank you. Can you please share the output format of the ABAP job.

Yes, landingPageConfig.json file is as it is and not changed. but when clicked get started button, nothing appears. When I checked the path, it is "/S4HanaCloud/IntegrationSuite/PurchaseOrderTable" but should it be "/simpleConfig/S4HanaCloud/IntegrationSuite/PurchaseOrderTable"? as the files are under simpleConfig folder?

<img width="758" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/f3786d73-d478-4134-9d6e-d790b9cb9782">

And do we need pass any values in "param" in ms teams app manifest file ?

<img width="578" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/83db1f8d-7214-4cdf-89c5-2f7a85b5c45f">


Thanks,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Yes, the path should be `/simpleConfig/S4HanaCloud/IntegrationSuite/PurchaseOrderTable`. This is likely why nothing is rendering from the landing page, as the paths specified for grabbing the tiles on the landing page does use `simpleConfig`.

Additionally, I see you are using S4 Hana Cloud - the setup for this is slightly different than the documentation we have for S4 on prem. However, I'm assuming this has already been setup correctly on your side. If it hasn't please refer to this [issue](https://github.com/SAP-samples/btp-bridge-framework/issues/32).

You do not need to pass in values in for "param" in the MS Teams app manifest file.

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Hi,

I changed it to "/simpleConfig/S4HanaCloud/IntegrationSuite/PurchaseOrderTable" but still the same as blank page. 

<img width="486" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/26a9d308-1a60-434e-a02c-13e401723323">


Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

That is strange. Could you please paste the value of the path field you are using in your landing page config for your S4 Hana Cloud tile?

Best,
Alex

**Comment by AFK-Python** [comment]
Hi Chanchal,

Perhaps check these three options of what could be going wrong:

Error Case: Bridge Framework Landing Page Not Showing Up After Click Get Started via Welcome Card
Root Case: The Path of frontend configuration files mention in the landingPageConfig.json is not correct.

Solutions:
 1. Open the Bridge Framework Config Server application folder, then go to `/public/frontend`. Make sure the project structure is the same as below, with exactly the same name.
```
  - config
      - nginx
      - public
           - backend
           - frontend
               - images
               - simpleConfig                        (this is a folder directory)
               - landingPageConfig.json      (this is a file)
           - notification
```

Make sure the landingPageConfig.json file is consumable after the deployment via URL `https://CONFIG-SERVER-HOST-NAME/frontend/landingPageConfig.json`.

 2. Under the simpleConfig folder, there should be a folder called S4HanaCloud/IntegrationSuite, with exactly the same name. Then their frontend configuration file should contains under it.
```
  - config
      - nginx
      - public
           - backend
           - frontend
               - images
               - simpleConfig                         (this is a folder directory, with exactly the same name)
                    - S4HanaCloud                         (this is a folder directory, with exactly the same name)
                       - IntegrationSuite                         (this is a folder directory, with exactly the same name)
                          - PurchaseOrderTable.json                        
            - landingPageConfig.json      (this is a file, with exactly the same name)
           - notification
```

In above example, make sure the PurchaseOrder.json configuration file is consumable after the deployment via URL `https://configure-server-host-name/frontend/simpleConfig/S4HanaCloud/IntegrationSuite/PurchaseOrderTable.json`.

 3. In the landingPageConfig.json file, the configuration should have the below structure

```
{
  "id": "landingPageConfig",         this must be the exactly same name.
  "path": "/",
  "solutions": [
    {
      "key": 1,
      "header": "Purchase Orders",
      "description": "S4HanaCloud IntegrationSuite",
      "path": "/S4HanaCloud/IntegrationSuite/PurchaseOrderTable"
    }
  ]
}
```

In the path, for the above examples, please make sure to mention the URI to consume the PurchaseOrderTable.json file.
