### ISSUE TITLE
values of .env file in backend

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#30]
Hi,

From where I can get the values for the following parameters in .env file of backend application.

```
# Auth
samlScope=<SAML_SCOPE>
samlResourceUrl=<SAML_RESOURCE_URL>
samlAlias=<SAML_ALIAS>

# Config server
configServerUrl=<CONFIG_SERVER_URL>

# Transcript Summary Model Token 
TranscriptSummaryModelAPIKey=<API_KEY_FOR_QUERYING_YOUR_SUMMARY_MODEL>
```

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

The `samlScope` comes from the bot's OAuth connection settings scope value. This can be found by navigating to the bot created, selecting 'Configuration' (under 'Settings') from the left side bar, and clicking on the OAuth connection that was created. In the right side bar that opens, the scopes string is the value of the `samlScope`.

The `samlResourceUrl` comes from xsuaa service with the application plan in BTP. You can search for this in your subaccount under 'Instances and Subscriptions'. After clicking on the xsuaa instance, a side panel should open up with more details about it. In this side panel, select 'View Credentials'. The first url value in the JSON is value of the `samlResourceUrl`.

The `samlAlias` can be found under the enterprise application. After navigating to the enterprise application, click on the link next to `Managed application in local directory`. On the page that opens up, select 'Single sign-on' (under 'Manage') from the left side bar. The `samlAlias` is the value that comes after the `/alias` portion of the logout and reply urls.

The config server should be set to the url of your config server app. This should be defined in the manifest.yaml file used to push the config server. The url should look like this: `https://<name_used>.cfapps.<cloud_foundry_api_region>.hana.ondemand.com/`.

Please see this [documentation page](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/transcript/Transcript%20Set%20Up.md#update-your-backend-env-file-with-the-necessary-information) for how to get the transcript summary model token.

Best,
Alex
