### ISSUE TITLE
Teams app uploaded but nothing happening

### ISSUE THREAD

**Issue by LyubomirDenkovAct** [SAP-samples/btp-bridge-framework#31]
Hello

I configure everything but after app is deployed on BTP and uploaded to teams nothing happening - no landing page and so on... how I can see any logs to see where is the problem ? 

Best 
Denkov

**Comment by AFK-Python** [comment]
Hi Denkov,

First, I want confirm if you used the docker container with automated setup. If that is the case, there is a `logs/` folder within the container that could help pinpoint the error.

However, if everything was setup via the automated setup without errors, then this is likely a .env issue or Azure resource issue. Either way (and even if manual setup was used), the logger tied to each application should provide some information on what went wrong. My suspicion would be the backend logs would be more useful. You should be able to see the logs of an application by navigating to the space level. From there, select the backend application, and you should see a logs section on the left side panel - click on that.

Do you receive any errors when trying to open the app in teams after the upload to teams? Please check the network tab from dev tools as well, this may provide useful information for debugging.

Happy to help with any follow-up questions, but please be careful if you are pasting anything in - some of the logs and errors contain sensitive information.

Best,
Alex

**Comment by LyubomirDenkovAct** [comment]
Hello

I use automation setup tool and everything is fine, but after deployment on teams I didnt see that page -> 
<img width="719" alt="WelcomeCard" src="https://github.com/SAP-samples/btp-bridge-framework/assets/139438212/74ef5759-d41d-4c20-96d6-a9d442aa23b1">

And we don't have S4 so do you have any hint how I can mock it and use the app just for test (demo)?
I want to make simple action by entering any value and show something in output.

Best,
Denkov

**Comment by AFK-Python** [comment]
Hi Denkov,

Unfortunately, there is no way to mock the app without the connection to S4. We strongly recommend working with an S/4HANA system admin to setup the ABAP job, destination services, and OAuth configuration of event mesh in the S/4HANA system. 

Alternatively, Bridge supports connections to C4C and SFSF, we would be happy to help you set up either of those situations, provided you have access to either of them. Either of these cases would allow you to enter values and show outputs.

Best,
Alex
