### ISSUE TITLE
S/4HANA Cloud Support

### ISSUE THREAD

**Issue by Backo123** [SAP-samples/btp-bridge-framework#32]
Dear Bridge Team,

According to this blog - https://blogs.sap.com/2022/09/14/bridge-framework-integration-framework-based-on-sap-btp-for-ms-teams-integrations-with-sap/. The Bridge Framework supports also S/4HANA Cloud.
Is this the case, because I don't see any guidance in the documentation how this is achieved?

Best regards
Vassil

**Comment by AFK-Python** [comment]
Hi Vassil,

I can better help you if you have a specific use case in mind for Bridge, or are stuck on a particular part of the setup. However, the [SAP S/4 Hana Cloud help pages](https://help.sap.com/docs/SAP_S4HANA_CLOUD?q=destination) are a useful starting place. I believe this [resource](https://help.sap.com/docs/SAP_S4HANA_CLOUD/0f69f8fb28ac4bf48d2b57b9637e81fa/5232d569d23b4c109834b688e2e2f4d5.html?q=btp%20destination) might be useful for connecting BTP and S4 Hana Cloud.

I should note that our [automation setup](https://github.com/SAP-samples/btp-bridge-framework/releases) does not help to configure BTP with S/4 Hana Cloud; however, you should be able to still use it for BTP and Azure resources. So I would still recommend looking into it and starting there, as this will handle the majority of the setup regardless of what system you plan on using.

Best,
Alex

**Comment by Backo123** [comment]
Hi Alex,

Thanks for your reply.
We were able to complete the automation setup, but all guides here in GitHub don't mention the S/4HANA Cloud integration. Can you confirm my assumptions?

For S/4HANA Cloud we would not need Cloud Connector and BTP Connectivity Service. To connect S/4HANA Cloud we just define it as a destination in BTP.
In S/4HANA Cloud we have similar OData service providing Purchase Order data.

Best Regards
Vassil

**Comment by AFK-Python** [comment]
Hi Vassil,

Yes, these points are correct. If you get stuck during configuration please let us know and we can help.

Best,
Alex
