### ISSUE TITLE
Automated setup 

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#33]
Hi Alex,

I am following the Automated setup but I am stucked here :
<img width="625" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/8da23e8a-3fbd-4efc-bcd5-cde887dcb5b9">

When I try to click on the link "step" it shows me something like this:
<img width="432" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/f0befce3-8995-4750-a014-7d1ebb2f90cd">

What changes should me made to get the frontend, backend and notification setup.

Thanks 
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

Could you point me to where you are finding this documentation from? I can't seem to find these steps in [the automated setup guide](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/automation/Automation%20Overview.md) linked in our README. If this is the mission guide, please ignore it and follow the guide linked in this repo (same link in the previous sentence). The mission can be useful, but it is slightly different than our samples repo.

**Note, you're going to need to update the config folders according to your use case in the automated pipeline**. This should be done before running the pipeline to avoid duplicate work. However, the config folder should have the same files and file structure as that on samples. To update and/or view the config relevant to code changes, go to `btp-bridge-framework/config/public`.

Best,
Alex
