### ISSUE TITLE
Error while logging in Azure by Automated setup

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#35]
Hi,

1: During Automated set up, I  am getting the following error, while executing the command : 

`pwsh /home/user/btp-bridge-framework/azure-configuration/CreateDeployment.ps1`

Error in pwsh.log: 
`Login status: [08/17/23 19:24:02] Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Subscription'`

<img width="859" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/2eecabb4-1bd6-4802-8863-7658ad376288">

2: Where should I run this command ?

<img width="689" alt="image" src="https://github.com/SAP-samples/btp-bridge-framework/assets/113780648/8bbea88e-41d5-46cc-a81f-63b3e004f722">

Br,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

First, please make sure you are using the [terraform version of the container](https://github.com/SAP-samples/btp-bridge-framework/releases/tag/v1.0.0-tf-regular) ([BTP free tier version](https://github.com/SAP-samples/btp-bridge-framework/releases/tag/v1.0.0-tf-free-tier)). If you are using the PowerShell version of the container, this could cause issues on apple silicon chips as PowerShell behavior is undefined on them.

Second, are you running the pipeline by using `./btpsa`? You shouldn't have to run each individual sub-script of the automated setup.

Third, that command can be run in a PowerShell terminal, which can be accessed by typing `pwsh` into the terminal. However, it shouldn't be used until after the tool has completed, and should only be used if you have the `"deployToTeams" ` field in `parameters.json` set to `true`.

Lastly, were you able to successfully enter the device code and grant Azure permission to use APIs for your account?

Best,
Alex

**Comment by ChanchalAgrawalMiku** [comment]
Thank you for your support. I have now completed manual setup and end-to-end working perfect as desired :)
