### ISSUE TITLE
Attachments in Purchase Orders

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#40]
Hi,

Can we send the PDF attachments of Purchase Orders to teams via Bridge Framework?

Br,
Chanchal.

**Comment by sap-weikun** [comment]
Hi ChanchalAgrawalMiku,

We are working on this feature and we will updates this repo once this functionality is available.

Best Regards,
Weikun Liu

**Comment by sap-weikun** [comment]
> Hi,
> 
> Can we send the PDF attachments of Purchase Orders to teams via Bridge Framework?
> 
> Br, Chanchal.

Hi Chanchal,

We are working on this feature and we will updates this repo once this functionality is available.

Best Regards,
Weikun Liu

**Comment by ChanchalAgrawalMiku** [comment]
Thank you,
